version: "3.9"

services:

  postgres-db:
    image: postgres:11-alpine
    container_name: postgres-db-hml
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.3.2
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    links:
      - postgres-db
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - KEY_SELECTOR_URL=false
      - COLLECT_METRICS=true
      - HLM_LOG_LEVEL=info
    volumes:
      - ../metrics/screenshots/:/screenshots
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.1
    container_name: selector-imitator-html
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium

  selenoid:
    image: healenium/hlm-selenoid:0.1.0
    container_name: selenoid-hml
    restart: on-failure
    ports:
      - "4444:4444"
    environment:
      - LIMIT=10
      - OVERRIDE_VIDEO_OUTPUT_DIR=DIRETORIO FORA DO CONTAINER CAMINHO ABSOLUTO
    volumes:
      - .:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./videos:/opt/selenoid/video/
    command: [
      "-container-network", "healenium",
      "-video-output-dir", "/opt/selenoid/video"]
    networks:
      - healenium

  selenoid-ui:
      image: aerokube/selenoid-ui:1.10.9
      container_name: selenoid-ui-hml
      restart: on-failure
      ports:
        - "8080:8080"
      command: [ "--selenoid-uri", "http://selenoid:4444" ]
      links:
        - selenoid
      networks:
        - healenium

networks:
  healenium:
    name: healenium